### ISSUE TITLE
Updated Braintree Payments / Apple Pay Support

### ISSUE THREAD

**Issue by Sam-Spencer** [RunSignUp-Team/RunSignUp-Apps#1]
Any idea if this project will ever update the payment system and support newer payment infrastructures and Apple Pay?

**Comment by runsignup** [comment]
We acquired RaceJoy in March. Our plan is to incorporate this open source app code into the RaceJoy App and add functionality for Apple Pay. Since it is one code base in RaceJoy, we might not be updating this code base.  What is your your interest?  You can send me email at bob.bickel at runsignup dot com.
